<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="3" total="5" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Beginning of demo03Test]]>
    </line>
    <line>
      <![CDATA[End of test]]>
    </line>
    <line>
      <![CDATA[Beginning of demo01Test]]>
    </line>
  </reporter-output>
  <suite name="Failed suite [My suite]" duration-ms="84" started-at="2020-08-12T14:10:53 IST" finished-at="2020-08-12T14:10:53 IST">
    <groups>
      <group name="odd">
        <method signature="DemoTestNG5.demo01Test(java.lang.String)[pri:0, instance:com.stackroute.automation.testng.DemoTestNG5@5d624da6]" name="demo01Test" class="com.stackroute.automation.testng.DemoTestNG5"/>
        <method signature="DemoTestNG5.demo03Test()[pri:0, instance:com.stackroute.automation.testng.DemoTestNG5@5d624da6]" name="demo03Test" class="com.stackroute.automation.testng.DemoTestNG5"/>
      </group> <!-- odd -->
    </groups>
    <test name="mytest1(failed)" duration-ms="84" started-at="2020-08-12T14:10:53 IST" finished-at="2020-08-12T14:10:53 IST">
      <class name="com.stackroute.automation.testng.DemoTestNG5">
        <test-method status="FAIL" signature="demo03Test()[pri:0, instance:com.stackroute.automation.testng.DemoTestNG5@5d624da6]" name="demo03Test" duration-ms="13" started-at="2020-08-12T14:10:53 IST" finished-at="2020-08-12T14:10:53 IST">
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[org/junit/Assert]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: org/junit/Assert
at com.stackroute.automation.testng.DemoTestNG5.demo03Test(DemoTestNG5.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.TestNG.privateMain(TestNG.java:1326)
at org.testng.TestNG.main(TestNG.java:1294)
Caused by: java.lang.ClassNotFoundException: org.junit.Assert
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
... 28 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
            <line>
              <![CDATA[Beginning of demo03Test]]>
            </line>
            <line>
              <![CDATA[End of test]]>
            </line>
          </reporter-output>
        </test-method> <!-- demo03Test -->
        <test-method status="FAIL" signature="demo01Test(java.lang.String)[pri:0, instance:com.stackroute.automation.testng.DemoTestNG5@5d624da6]" name="demo01Test" duration-ms="5" started-at="2020-08-12T14:10:53 IST" finished-at="2020-08-12T14:10:53 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[kurinchi]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.NoClassDefFoundError">
            <message>
              <![CDATA[org/junit/Assert]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.NoClassDefFoundError: org/junit/Assert
at com.stackroute.automation.testng.DemoTestNG5.demo01Test(DemoTestNG5.java:27)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1249)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.TestNG.privateMain(TestNG.java:1326)
at org.testng.TestNG.main(TestNG.java:1294)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NoClassDefFoundError -->
          <reporter-output>
            <line>
              <![CDATA[Beginning of demo01Test]]>
            </line>
          </reporter-output>
        </test-method> <!-- demo01Test -->
      </class> <!-- com.stackroute.automation.testng.DemoTestNG5 -->
    </test> <!-- mytest1(failed) -->
  </suite> <!-- Failed suite [My suite] -->
</testng-results>
